"""add fk constraints and asset indexes

Revision ID: 94aecb2974d2
Revises: d347d8e39e65
Create Date: 2026-06-27 16:51:31.461465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94aecb2974d2'
down_revision: Union[str, None] = 'd347d8e39e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'asset_relationships', 'assets', ['target_asset_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'asset_relationships', 'assets', ['source_asset_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset_relationships', type_='foreignkey')
    op.drop_constraint(None, 'asset_relationships', type_='foreignkey')
    # ### end Alembic commands ###
